### ISSUE TITLE
Issue description is empty

### ISSUE THREAD

**Issue by ch264** [peter-evans/link-checker#8] opened 2019-11-27 19:47 UTC
I have implemented the link checker and it runs and also creates an issue, but the description in the issue is empty. 

Expected would be to see the error link in the description.

**Comment by peter-evans** [comment] 2019-11-28 00:02
Hi @ch264 

I'm looking at your workflow here: https://github.com/ch264/Gatsby_site/blob/linkchecker/.github/workflows/brokenlink.yml

The problem is that the following line is not correct. By default, link-checker outputs its results to a file at the path `./link-checker/out.md`.
```
ISSUE_CONTENT_FILEPATH: ./example-content/output.md
```
Change the above line to this:
```
ISSUE_CONTENT_FILEPATH: ./link-checker/out.md
```
Note that you don't need to create an empty file at that path. The file is just created and used during the actions run.

**Comment by ch264** [comment] 2019-12-02 20:03
Hi @peter-evans,

Thanks for your fast reply. I changed the code and the issues are still empty https://github.com/ch264/Gatsby_site/issues/52

I saw that an out.md file has now been created and it is also empty. I assume that is why the description is empty?

**Comment by peter-evans** [comment] 2019-12-03 08:38
Now the problem is that an empty `out.md` file was committed to the repository.
https://github.com/ch264/Gatsby_site/blob/master/link-checker/out.md

You need to delete that file. It's existence means that the `create-issue-from-file` action always finds it and creates a blank issue.

**Comment by peter-evans** [comment] 2019-12-03 08:44
By the way, I'm not sure if this is what you expect, but the current test link you have won't be detected as "broken." You can see the output here. The link is marked "OK."

![image](https://user-images.githubusercontent.com/18365890/70034085-fb905d80-15f3-11ea-829a-bd6292e3dbb3.png)

The reason for this is that the site is redirecting to a 404 page and actually seems to be returning a `403 Forbidden`. [Liche](https://github.com/raviqqe/liche), the tool this action uses, doesn't count this as broken.

**Comment by ch264** [comment] 2019-12-03 18:50
Oh ok I understand. I though there was complete log of all scanned links being output into the description instead of only broken link. Thank you very much for clarifying 😄

**Comment by peter-evans** [comment] 2019-12-03 23:16
No problem. Closing this issue for now.

**Closed by peter-evans** 2019-12-03 23:16 UTC
